### ISSUE TITLE
Ошибка на корректной программе

### ISSUE THREAD

**Issue by kajigor** [MariaChizhova/Formal-Languages#4]
[t05.txt](https://github.com/MariaChizhova/Formal-Languages/files/5334191/t05.txt)
[t13.txt](https://github.com/MariaChizhova/Formal-Languages/files/5334192/t13.txt)
[t19.txt](https://github.com/MariaChizhova/Formal-Languages/files/5334193/t19.txt)

Идентификаторы состоят из букв латинского алфавита в любом регистре, могут содержать цифры и символ нижнего подчеркивания `_`, но не начинаются на цифру

**Comment by MariaChizhova** [comment]
Исправлено.
